### ISSUE TITLE
Merge work from external branch and fix

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gmljpx20#1]
Work has been advance in this branch. Please merge it to this project. It is not building successfully. Seems like some tests have not been implemented. Please fix

```
Tests in error: 
 VerifyCoreTests.rootInstancecontainsFileFeatures:170 » MissingResource Can't f...
 VerifyCoreTests.rootInstancecontainsGMLJP2fileInternalRefToXMLBox:290 » MissingResource
 VerifyCoreTests.rootInstancecontainsGMLJP2fileJPXJP2Compatible:230 » MissingResource
 VerifyCoreTests.rootInstancecontainsGMLJP2fileJp2OtherOuterBox:250 » MissingResource
 VerifyCoreTests.rootInstancecontainsGMLJP2fileJp2OuterBox:240 » MissingResource
 VerifyCoreTests.rootInstancecontainsGMLJP2fileXMLSignaledCorrectly:220 » MissingResource
 VerifyCoreTests.rootInstancecontainsGmlcovCoverageContainer:150 » MissingResource
 VerifyCoreTests.rootInstancecontainsInternalRefToCodestream:300 » MissingResource

Tests run: 50, Failures: 17, Errors: 8, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.498 s
[INFO] Finished at: 2016-03-03T16:43:33-05:00
[INFO] Final Memory: 26M/317M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project ets-gmljpx20: There are test failures.
```

https://github.com/AlbertoSN/GMLJP-v2

**Comment by rjmartell** [comment]
Please create a pull request.

@AlbertoSN

**Comment by rjmartell** [comment]
Note that in the XPath expression passed to the `XMLUtils.evaluateXPath` method, qualified element names must be specified if they reside in some target namespace (e.g. //gml:RectifiedGrid). A namespace binding for the "gml" prefix is predefined, but others must be explicitly declared.

**Comment by rjmartell** [comment]
There are 25 failing unit tests in `VerifyCoreTests` that fall into three groups:
- java.util.MissingResourceException: 8 
- com.sun.org.apache.xpath.internal.domapi.XPathStylesheetDOM3Exception: 15 
- java.lang.AssertionError ("XML box not found in codestream"): 2 

[org.opengis.cite.gmljpx20.core.VerifyCoreTests.txt](https://github.com/opengeospatial/ets-gmljpx20/files/163626/org.opengis.cite.gmljpx20.core.VerifyCoreTests.txt)

The `XPathStylesheetDOM3Exception` errors all appear to be due to missing namespace bindings or qualified element names in XPath expressions ("Prefix must resolve to..."). Perhaps the unexpected AssertionError occurrences are bugs in utility methods? A MissingResourceException usually indicates a missing error message entry in MessageBundle*.properties (in src/main/resources)

**Comment by rjmartell** [comment]
The GMLJP-v2 repo is not a fork of this one. Try creating a branch and a pull request against the new branch.

**Comment by AlbertoSN** [comment]
I created new branch called PR9m but I can't do pull request. Shows message "It seems you do not have permission to push your changes to this repository". 

In another vein, I got some doubts about errors that is giving:
- The keys referred to several errors, I understood that they were messages to inform where the error is occurring. I also understood that it is a String and serves only to display the text of "assert" if null or may not be located in ErrorMessageKeys.java. How can give a mistake a text message shown to the person who tests the images? I do not know if I understand this well because I do not see much sense. Apart from that, it's like the reference is not found, and the truth, all in the java file mentioned.
- Another question is about the xpath, what namespace must aim? According to the OGC specification 08-085r4 where I performed the test, the first test in fact refers to "http://www.opengis.net/gmlcov/1.0" but others do not, so I understood that they should have namespaces. The question is if the error occurred must refer to elements of http://www.opengis.net/gmlcov/1.0 forms, why in others not listed or mentions any reference?

I wait your response.

Thanks.

**Comment by rjmartell** [comment]
When using message keys to provide (localized) error messages, there are two steps:
1. Add a new key to `ErrorMessageKeys` in the root package (e.g. GMLJP2_INTERNAL_REF)
2. Add a matching entry in the resource bundles at src/main/resources/*/MessageBundle*.properties (this includes the message content) 

Example:

```
gmljp2-internal-ref = Error message with parameters if desired
```

**Comment by rjmartell** [comment]
For any GML (3.2) element, you can use the "gml" prefix since there is a predefined binding for this (in `*.util.NamespaceBindings#withStandardBindings`). You could add more bindings to this standard set; otherwise they are declared when needed in a Map (key: namespace) as shown below:

```
Map<String, String> nsBindings = new HashMap<String, String>();
nsBindings.put(Namespaces.WFS, "wfs");
// or just use Collections.singletonMap(K key, V value) if only one binding is required
result = XMLUtils.evaluateXPath(contextNode, "//wfs:member/*", nsBindings);
```

The declared prefix may then be used in the XPath expression. Note that the prefix in the expression does not have to match what appears in the actual instance; the namespace name (URI) is significant, but the prefix is not.

The GML root instance in the test image contains elements in the namespaces listed below.

| Namespace name | Prefix |
| --- | --- |
| `http://www.opengis.net/gml/3.2` | gml |
| `http://www.opengis.net/gmljp2/2.0` | gmljp2 |
| `http://www.opengis.net/gmlcov/1.0` | gmlcov |
| `http://www.opengis.net/swe/2.0` | swe |

**Comment by rjmartell** [comment]
The usual process for contributing new tests or bug fixes is outlined in the README under "How to contribute":
1. Fork the opengeospatial/ets-gmljpx20 repo.
2. Create a new topic/task branch in your forked repo; commit all changes here.
3. Create a pull request

**Comment by AlbertoSN** [comment]
Thanks Richard, I have already made changes

**Comment by rjmartell** [comment]
Great. Please create a pull request when you're ready so the changes can be merged here.

**Comment by bermud** [comment]
PR has been submitted ( #2 ) 
@keshav-nangare, please investigate why it is not building and then merge. Thank you!

**Comment by AlbertoSN** [comment]
i[cid:image001.jpg@01D1D96B.93ED5E30]
This is my info github desktop app, If u want I send u my code. Any idea?

De: Luis Bermudez [mailto:notifications@github.com]
Enviado el: viernes, 8 de julio de 2016 16:26
Para: opengeospatial/ets-gmljpx20 ets-gmljpx20@noreply.github.com
CC: AlbertoSN al_sn52@hotmail.com; Mention mention@noreply.github.com
Asunto: Re: [opengeospatial/ets-gmljpx20] Merge work from external branch and fix (#1)

PR has been submitted ( #2https://github.com/opengeospatial/ets-gmljpx20/pull/2 )
@keshav-nangarehttps://github.com/keshav-nangare, please investigate why it is not building and then merge. Thank you!

**Comment by keshavnangare** [comment]
Test case are failing with the "Prefix must resolve to".

Input xml file [romagmljp2-collection2-rreq7](https://github.com/opengeospatial/ets-gmljpx20/files/359920/romagmljp2-collection2-rreq7.txt)

In test `"containsCRSrectifiedGridCoverage"`,the evaluateXpath method having expression `"//RectifiedGrid:*"` but this element is not present in the input xml, it has the prefix "gml:RectifiedGrid" in input xml but we are passing the `"GMLCOV, "cov"`.

Similarly in the test "containsGmlcovNilValues",  `expression= "//nil-values:*"`, this test is expecting the element "//nil-values:*" is exist in input xml but this element is not present in the input xml.

Can you please elaborate on this, what is the expected output?

**Comment by bermud** [comment]
@AlbertoSN, can you please take a look at the comment Keshav made? I think there is an issue with prefixes and namespaces.

**Comment by lgoltz** [comment]
I think PR #2 should be closed without merging. The PR handles two different thinks:
 * Missing error messages (#6), but the messages are incomplete.
 *  Fixing of XPath expressions in CoreTests (a new issue was created: #10), this is also handled in #3
