### ISSUE TITLE
Wrong xpath expression in containsGmlRangeTypeDataRecordUom

### ISSUE THREAD

**Issue by alunacob** [opengeospatial/ets-gmljpx20#27]
I believe this is wrong:
https://github.com/opengeospatial/ets-gmljpx20/blob/d861bf3c930800f318db0ea2be79c2af5c1d4565/src/main/java/org/opengis/cite/gmljpx20/core/CoreTests.java#L398

and it should use local-name()

**Comment by dstenger** [comment]
Thank you for reporting.
@keshav-nangare Can you please check the reported issue?

**Comment by EmDevys** [comment]
All
I commented on the github (#EmDevys) and provided a correct example roma4326-2b.
The one used in the github (romagmljp2-collection2-rreq7.jp2) is incorrect (empty <gmlcov:rangeType/>)

Please use the example provided instead, and hopefully it will validate.
Otherwise I may investigate further

Emmanuel

De : Emmanuel Devys
Envoyé : mardi 12 novembre 2019 19:03
À : 'opengeospatial/ets-gmljpx20'; opengeospatial/ets-gmljpx20
Cc : Subscribed
Objet : RE: [opengeospatial/ets-gmljpx20] Wrong xpath expression in containsGmlRangeTypeDataRecordUom (#27)

I guess Lucio has provided a sample such as the attached file (gmljp2) which should validate.

Unfortunately the examples under http://schemas.opengis.net/gmljp2/2.0/examples/ are invalid, because they have an empty rangeType element…
I kindly requested these examples to be corrected.

Hoping this is now clear.


De : dstenger [mailto:notifications@github.com]
Envoyé : mardi 12 novembre 2019 17:18
À : opengeospatial/ets-gmljpx20
Cc : Subscribed
Objet : Re: [opengeospatial/ets-gmljpx20] Wrong xpath expression in containsGmlRangeTypeDataRecordUom (#27)


Thank you for reporting.
@keshav-nangare<https://github.com/keshav-nangare> Can you please check the reported issue?

**Comment by keshavnangare** [comment]
Fixed with this commit: 906c93c8b552e436b8fbb3494b1f67b6f7396862
