### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-gmljpx20#7]
Two unit tests are failing:

- VerifyCoreTests.rootInstancecontainsGMLJP2fileStyle
- VerifyCoreTests.rootInstancecontainsUomByReference

Both tests check the `romagmljp2-collection2-rreq7.jp2` file in the src/test/resources/jp2 directory. Is this the correct file?

**Comment by rjmartell** [comment]
The GML root instance in the test file is attached below. It doesn't appear to contain any uom references or style information.

[gmljpx-ccid1.txt](https://github.com/opengeospatial/ets-gmljpx20/files/804241/gmljpx-ccid1.txt)

**Comment by luciocola** [comment]
Correct the two test failing are due to:
1) GMLJP2fileStyle for lack of specs in the symbology (I am currently drafting a proposal)
2) lack of example (more examples will be available soon)

**Comment by bermud** [comment]
@luciocola, I see we have the latest in master branch. Have you been able to advance further this test and can you please provide some test data?

**Comment by bermud** [comment]
@luciocola, what is the status of this test? I have added @dstenger to this issue so he can support you in the future.

**Comment by luciocola** [comment]
Hi,
I uploaded the last version sometime ago if you could be so kind to check it and let me know if you need changes I am more than happy to support.
I have also prepared another imagery for test.
Regards



[cid:image002.png@01D36220.1DFB2470]




Lucio Colaiacomo
Chief Technology Officer

.
Apdo. de Correos 511, 28850 Torrejón de Ardoz,

Madrid – Spain

Phone +34916786075

Fax +34 91 678 60 06



Lucio.Colaiacomo@satcen.europa.eu

www.satcen.europa.eu<http://www.satcen.europa.eu>

**Comment by bermud** [comment]
@dstenger, can you please investigate where we are with this test. I think Lucio provided a PR https://github.com/opengeospatial/ets-gmljpx20/pull/3) that has not been investigated/merged. Thank you.

**Comment by dstenger** [comment]
I am still getting unit test errors. Please see: https://github.com/opengeospatial/ets-gmljpx20/pull/3#issuecomment-376445372

**Comment by luciocola** [comment]
Hi…
I found the same but the error is due to .xsd file reference …
Could you tell me which is the correct path ?
See error attached…
Any help is welcome
regards


[cid:image001.png@01D3CCFA.9762A0F0]






[cid:image002.png@01D3CCFA.B8051EF0]<https://www.satcen.europa.eu/images/SAtcen_Color_RGB.jpg>




Lucio Colaiacomo
Chief Technology Officer

.

.
Apdo. de Correos 511, 28850 Torrejón de Ardoz,

Madrid – Spain

Phone +34916786075

Fax +34 91 678 60 06



Lucio.Colaiacomo@satcen.europa.eu

www.satcen.europa.eu<http://www.satcen.europa.eu>

**Comment by EmDevys** [comment]
All
Not sure it will be of any help, as this is trivial to me, the relevant schemas are at :
http://schemas.opengis.net/gmljp2/2.0/gmljp2.xsd
http://schemas.opengis.net/gmlcov/1.0/gmlcovAll.xsd
http://schemas.opengis.net/gml/3.2.1/gml.xsd

As I did not see any attached error file, I am unsure about the diagnosis…
Hoping this helps
Cheers
Emmanuel

De : luciocola [mailto:notifications@github.com]
Envoyé : jeudi 5 avril 2018 17:01
À : opengeospatial/ets-gmljpx20
Cc : Subscribed
Objet : Re: [opengeospatial/ets-gmljpx20] Failing unit tests (#7)

Hi…
I found the same but the error is due to .xsd file reference …
Could you tell me which is the correct path ?
See error attached…
Any help is welcome
regards


[cid:image001.png@01D3CCFA.9762A0F0]






[cid:image002.png@01D3CCFA.B8051EF0]<https://www.satcen.europa.eu/images/SAtcen_Color_RGB.jpg>




Lucio Colaiacomo
Chief Technology Officer

.

.
Apdo. de Correos 511, 28850 Torrejón de Ardoz,

Madrid – Spain

Phone +34916786075

Fax +34 91 678 60 06



Lucio.Colaiacomo@satcen.europa.eu

www.satcen.europa.eu<http://www.satcen.europa.eu>

**Comment by bermud** [comment]
@dstenger or @lgoltz , what is the status of this issue and test?

**Comment by lgoltz** [comment]
I've merged PR #9 (automatically to branch opengeospatial:satcen and manually from  opengeospatial:satcen to opengeospatial:master).

` mvn clean install` can be executed without failures.
